### ISSUE TITLE
Easier way to switch to different AWS accounts 

### ISSUE THREAD

**Issue by baopham** [baopham/laravel-dynamodb#14]
Currently, user has to override the `setupDynamoDb()` method.

**Comment by zoul0813** [comment]
Was looking into this issue a while back.  I found it odd that the DynamoDb config was stored in `config/services.php` instead of `config/database.php` ... 

If we moved the config to `config/database.php` and used named connections, each named connection could be assigned to a different AWS account.  We could then use the `on('connection-name')` method to use different named connections (changing access keys, regions, etc).

DynamoDbClientService could then use the connection name as an array key, and instantiate a new `DynamoDbClient()` instance for each named connection using the connections config.

DynamoDbClientService's `getClient()` could then return the 'default' connection, and accept a connection name as a parameter.  The Eloquent Model's `on($connection = null)` method sets the connection name on the model, so the user can just call `Model::on('named-connection')->find($id);` ... all the references to $this->client in DynamoDbQueryBuilder would then be replaced with $this->getClient() which would pass the query's "connection name" to DynamoDbClientService to retrieve the appropriate instance.

Thoughts?

**Comment by baopham** [comment]
I didn't want to have it in `config/database.php` because this library is not meant to be a DB driver (like laravel-mongodb). You can see that since the model needs to extends `DynamoDbModel`. 
Main reason is that from my experience, DynamoDb is not suitable to be the default DB, it only works well for specific cases.

But we can have a separate config for dynamodb and follow `config/database.php` approach. In this file, the user can define the default dynamo account.

**Comment by zoul0813** [comment]
I'm working on an idea at the moment, currently using `config/database.php` but that can of course be switched to something like `config/dynamodb.php`.  I think I almost have it, just working on testing out the connection switching now.  Once I have something usable, I'll let you take a look at my branch and see what you think.

**Comment by baopham** [comment]
That is awesome! 🎉

**Comment by zoul0813** [comment]
Ok, here's the first draft ... :)

https://github.com/zoul0813/laravel-dynamodb/commit/de5162556584029532099fe132e59aebf386b96c 

Unfortunately, the code fails most of the tests ... because of the tests relying on `$this->dynamoDbClient`.  We'd likely have to introduce a mock config into the tests that provides the config/dynamodb.php values so DynamoDbClientService can still use the Symfony/Laravel Config repository during the tests.

```Tests: 91, Assertions: 32, Errors: 86.```

However, in my local tests ... the code works as expected.  I tested it by simply setting up two configs for the same DynamoDb configuration.  One config had debug enable, the other did not.  I then wrote a simple test route in my laravel project ... 

```
  Route::get('/test-named-connections', function() {
    $items = null;
    if(Request::has('debug')) {
      $items = App\Items::on('dynamodb-debug')->all();
    } else {
      $items = App\Items::all(); // uses default connection name ('dynamodb')
    }
    dd($items);
  });
```
The result of this test was that by adding `debug=1` to the query string, I was able to enable/disable debugging on my DynamoDb connection without updating the config ... since I could just toggle between connections.

Obviously, much more advanced scenarios could be used here ... for example using a different AWS Key/Secret or switching Regions ... but my preliminary tests show that switching connections "by name" using Eloquents `on("connection-name")` method works.

The updates still a little rough, but I think it's a solid start?

**Comment by zoul0813** [comment]
Alright, modified ModelTest.php and now all the tests pass ... I added the $config param back to the constructor for DynamoDbClientService and pass `config('dynamodb')` to it in the DynamoDbProvider ... and I modified the config array in ModelTest to match, using the local test database.

```> phpunit
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

................................................................. 65 / 91 ( 71%)
..........................                                        91 / 91 (100%)

Time: 2.9 seconds, Memory: 48.00MB

OK (91 tests, 276 assertions)```
