### ISSUE TITLE
How to print recently executed query?

### ISSUE THREAD

**Issue by testsoftuvo** [baopham/laravel-dynamodb#163]
**Describe the bug**
I want to analysis what query is executed current. by my all conditions.

**Schema**

* Laravel: 5.4
* laravel-dynamodb: latest

**Comment by baopham** [comment]
There are 2 ways:

1. https://github.com/baopham/laravel-dynamodb#tosql-style
2. Log all the queries by setting this to true: https://github.com/baopham/laravel-dynamodb/blob/master/config/dynamodb.php#L38

Hope that helps! I'll close this one for now since I think that answers your question. But feel free to come back with more info!
