### ISSUE TITLE
Search with insensitive case

### ISSUE THREAD

**Issue by WendellAdriel** [baopham/laravel-dynamodb#177]
I'm trying to search for a word on two different fields

```
Model::where('field_a', 'contains', $filter)->orWhere('field_b', 'contains', $filter)->get();
```
The thing is that in one of these fields the word can be capitalized and when this happens, it doesn't get the record. Is there any way to query in a case insensitive way?

**Comment by zoul0813** [comment]
Check the DynamoDB docs from AWS on filter expressions.

This library doesn’t enhance or otherwise alter the DynamoDB query language, and only wraps it in an “Eloquent” way.

Possible solutions may be found [here](https://stackoverflow.com/questions/44284045/query-dynamodb-with-case-insensitive-condition)

I’d recommend ElasticSearch, but storing a lowercased version of the value may also work for very limited use cases.  This could be done automatically with a model observer than listens for “save” and stores a lowercased version of specific fields in a “fieldNameLower” property or something similar.

**Comment by WendellAdriel** [comment]
Thank you so much, just wanted to know if the library had something that did this automatically and thanks for the link and the possible solutions!!! I'll think which solution will be better for our use cases!!!
