### ISSUE TITLE
Support for latest laravel (6.2.0)? Or alternative?

### ISSUE THREAD

**Issue by foo123** [baopham/laravel-dynamodb#210]
The title says it all. Any way to use with latest laravel 6.2.0, or what are the alternatives?

Thank you

**Comment by ejeanneaubc** [comment]
👍

**Comment by YuK1Game** [comment]
want too...

**Comment by cokita** [comment]
Please, me too!!!

**Comment by bel123** [comment]
the same!!

**Comment by FrenchMajesty** [comment]
Yea this is quite bothersome... Sighs versioning will be the death of me!

**Comment by rennokki** [comment]
I have managed to work this out: https://packagist.org/packages/rennokki/dynamodb

The version has to be 5.0.0

**Comment by rennokki** [comment]
Managed to do this in a separate package: https://github.com/rennokki/dynamodb

It's not a fork to make sure it can scale independently and start from ground up with Laravel ^6.0. All namespaces use `Rennokki` instead of `BaoPham`. All contributors are kept as well as the original author.

I'll look forward in the next days (Friday ig) to refactor some of the bits, fix the docs and maybe work out on some migration stuff.

**Comment by reedknight** [comment]
+1

**Comment by baopham** [comment]
Sorry everyone for being so quiet for the last few months. If anyone is interested in maintaining this repro, let me know here #213
