### ISSUE TITLE
[Question] Working with Realtionships

### ISSUE THREAD

**Issue by joshhornby** [baopham/laravel-dynamodb#4]
Using this package is it possible to use the Laravel relationships? 

For example I have the following structure in Dynamo

| Table Name  | Hash Key | Range Key |
| ------------- | ------------- | ------------- |
| Forum | id |   |
| Thread | id  | forum |

So a thread belongs to a forum, is there a way to hook this up using this package?

**Comment by ruskiyos** [comment]
Out of curiosity, what would the expected behavior be? Since a thread requires a Hash and Range key, already have the Id of the Forum, so why not just query it directly?

I guess if you used the same approach as laravel relationship classes, that could be possible.
But DynamoDB is NoSQL, so it's not really meant to be used as a relational database...

**Comment by baopham** [comment]
Valid points from @ruskiyos. I'm a bit hesitant to support relationship. 

If you need relationship regardless, can you add a helper method to the model Thread `getForum()` and query based on the forum id?

**Comment by joshhornby** [comment]
Points taken @ruskiyos I was thinking more along the lines of I didn't want to do two queries when I normally could do one by using Laravel `with` function.
